// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type StorageInitParameters struct {

	// The ID of the region that you want the object storage to be deployed in.
	ClusterID *float64 `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// The description you want to give your object storage.
	Label *string `json:"label,omitempty" tf:"label,omitempty"`

	// The ID of the tier to deploy the storage under.
	TierID *float64 `json:"tierId,omitempty" tf:"tier_id,omitempty"`
}

type StorageObservation struct {

	// The ID of the region that you want the object storage to be deployed in.
	ClusterID *float64 `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Date of creation for the object storage subscription.
	DateCreated *string `json:"dateCreated,omitempty" tf:"date_created,omitempty"`

	// The id of the object storage subscription.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The description you want to give your object storage.
	Label *string `json:"label,omitempty" tf:"label,omitempty"`

	// The location which this subscription resides in.
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// The region ID of the object storage subscription.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// The hostname for this subscription.
	S3Hostname *string `json:"s3Hostname,omitempty" tf:"s3_hostname,omitempty"`

	// Current status of this object storage subscription.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// The ID of the tier to deploy the storage under.
	TierID *float64 `json:"tierId,omitempty" tf:"tier_id,omitempty"`
}

type StorageParameters struct {

	// The ID of the region that you want the object storage to be deployed in.
	// +kubebuilder:validation:Optional
	ClusterID *float64 `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// The description you want to give your object storage.
	// +kubebuilder:validation:Optional
	Label *string `json:"label,omitempty" tf:"label,omitempty"`

	// The ID of the tier to deploy the storage under.
	// +kubebuilder:validation:Optional
	TierID *float64 `json:"tierId,omitempty" tf:"tier_id,omitempty"`
}

// StorageSpec defines the desired state of Storage
type StorageSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            StorageParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider StorageInitParameters `json:"initProvider,omitempty"`
}

// StorageStatus defines the observed state of Storage.
type StorageStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        StorageObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Storage is the Schema for the Storages API. Provides a Vultr private object storage resource. This can be used to create, read, update and delete object storage resources on your Vultr account.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,vultr}
type Storage struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.clusterId) || (has(self.initProvider) && has(self.initProvider.clusterId))",message="spec.forProvider.clusterId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.tierId) || (has(self.initProvider) && has(self.initProvider.tierId))",message="spec.forProvider.tierId is a required parameter"
	Spec   StorageSpec   `json:"spec"`
	Status StorageStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// StorageList contains a list of Storages
type StorageList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Storage `json:"items"`
}

// Repository type metadata.
var (
	Storage_Kind             = "Storage"
	Storage_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Storage_Kind}.String()
	Storage_KindAPIVersion   = Storage_Kind + "." + CRDGroupVersion.String()
	Storage_GroupVersionKind = CRDGroupVersion.WithKind(Storage_Kind)
)

func init() {
	SchemeBuilder.Register(&Storage{}, &StorageList{})
}
