apiVersion: vultr.vultr.upbound.io/v1alpha1
kind: Kubernetes
metadata:
  annotations:
    meta.upbound.io/example-id: vultr/v1alpha1/kubernetes
  labels:
    testing.upbound.io/example-name: k8
  name: k8
spec:
  forProvider:
    label: k8-provisioned-by-crossplane
    nodePools:
    - autoScaler: true
      label: crossplane-k8-worker
      maxNodes: 2
      minNodes: 1
      nodeQuantity: 1
      plan: vc2-2c-4gb
    region: lax
    version: v1.25.6+2